---
title: "P8105 homework 5"
author: "Pengyuan Su (ps3195)"
date: "11/12/2020"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(purrr)

set.seed(51)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1

Read in the data.

```{r}
homicide_df = 
  read_csv("homicide_data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved",
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```


Let's look at this a bit

```{r}
aggregate_df = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved), 
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>% 
  broom::tidy()
```

Try to iterate ........

```{r}
results_df = 
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```



```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```



```{r, error = TRUE}
city_prop_test = function(df) {
  
  n_unsovled ...
  n_total ... 
  
  prop.test(.....)
  
}
homicide_df = 
  read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved",
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL") %>% 
  nest(data = resolved)
```


## Problem 2


#### read and tidy data

```{r}
p2_df = 
  tibble(
    name = list.files(path = "data")
  ) %>% 
  mutate(
    path = str_c("data/", name),
    data = map(path, read_csv),
    name = str_remove(name, ".csv"),
    
  ) %>% 
  select(-path) %>%
  separate(name, into = c("arm", "subject_id")) %>%
  mutate(
    arm = recode(arm, "con" = "control", "exp" = "experiment")
  ) %>% 
  unnest(data) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "observations",
    names_prefix = "week_"
  )

p2_df %>% 
  knitr::kable()
```

#### spaghetti plot 


```{r}
sph_plot = 
  p2_df %>% 
  unite("subject", c(arm, subject_id), sep = " ", remove = F) %>%
  ggplot(aes(x = week, y = observations, group = subject, color = subject)) +
  geom_path(alpha = 0.7)

sph_plot
```


## Problem 3


#### set function

```{r}
sim_mean_p = function(n = 30, mu, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      t.test(x, mu = 0, conf.level = 0.95) %>% broom::tidy() %>% select(p.value)
    )

}

```

#### Set μ=0. Generate 5000 datasets from the model

$x\sim N(\mu,\sigma)$

```{r}
output_mu_0 = vector("list", 5000)

for (i in 1:5000) {
  output_mu_0[[i]] = sim_mean_p(mu = 0)
}

sim_results = bind_rows(output_mu_0)

```




